---
- name: Import Server configuration profile
  hosts: idrac
  gather_facts: false
  vars_files:
    - ../vars_files/credentials.yml
  roles:
    - dellemc.openmanage.idrac_import_server_config_profile
